spring:
  application:
    name: service-registry
  config:
    import: 'optional:configserver:'
  profiles.active: dev
  cloud:
    config:
      uri: http://localhost:9090
      username: nttdata
      password: nttdata$
